# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "Target", # <tarchitect>
  "Parameter", # <tarchitect>
  "Input", # <tarchitect>
  "import_script", # <tarchitect>
  NULL
))
